name: Update JSON and Create Pull Request

on:
    schedule:
        # Run at 9:00, 12:00, 15:00, and 18:00 UTC from Monday to Friday
        - cron: '0 9 * * 1-5'
        - cron: '0 12 * * 1-5'
        - cron: '0 15 * * 1-5'
        - cron: '0 18 * * 1-5'
    workflow_dispatch: # Add this line to enable manual triggering

jobs:
    update-json:
        runs-on: ubuntu-latest
        env:
            NODE_ENV: production
            BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run script to update JSON
              run: npm start

            - name: Commit and push changes
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add .
                  git commit -m 'Update JSON file'
                  git push

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: Update JSON file
                  title: Update JSON file
                  body: Automated PR to update JSON file
                  branch: update-json-file
